-- +goose Up
-- Currency names are versioned CLDR resources, not accounting metadata.
ALTER TABLE currencies DROP COLUMN name_en, DROP COLUMN name_zh;

-- +goose Down
-- Restore the exact labels shipped by migration 00003 for binary rollback.
ALTER TABLE currencies ADD COLUMN name_en text, ADD COLUMN name_zh text;
UPDATE currencies AS c SET name_en = labels.name_en, name_zh = labels.name_zh
FROM (VALUES
('AED','United Arab Emirates Dirham','阿联酋迪拉姆'),
('AFN','Afghan Afghani','阿富汗尼'),
('ALL','Albanian Lek','阿尔巴尼亚列克'),
('AMD','Armenian Dram','亚美尼亚德拉姆'),
('AOA','Angolan Kwanza','安哥拉宽扎'),
('ARS','Argentine Peso','阿根廷比索'),
('AUD','Australian Dollar','澳大利亚元'),
('AWG','Aruban Florin','阿鲁巴弗罗林'),
('AZN','Azerbaijani Manat','阿塞拜疆马纳特'),
('BAM','Bosnia-Herzegovina Convertible Mark','波斯尼亚-黑塞哥维那可兑换马克'),
('BBD','Barbadian Dollar','巴巴多斯元'),
('BDT','Bangladeshi Taka','孟加拉塔卡'),
('BHD','Bahraini Dinar','巴林第纳尔'),
('BIF','Burundian Franc','布隆迪法郎'),
('BMD','Bermudan Dollar','百慕大元'),
('BND','Brunei Dollar','文莱元'),
('BOB','Bolivian Boliviano','玻利维亚诺'),
('BRL','Brazilian Real','巴西雷亚尔'),
('BSD','Bahamian Dollar','巴哈马元'),
('BTN','Bhutanese Ngultrum','不丹努尔特鲁姆'),
('BWP','Botswanan Pula','博茨瓦纳普拉'),
('BYN','Belarusian Ruble','白俄罗斯卢布'),
('BZD','Belize Dollar','伯利兹元'),
('CAD','Canadian Dollar','加拿大元'),
('CDF','Congolese Franc','刚果法郎'),
('CHF','Swiss Franc','瑞士法郎'),
('CLP','Chilean Peso','智利比索'),
('CNY','Chinese Yuan','人民币'),
('COP','Colombian Peso','哥伦比亚比索'),
('CRC','Costa Rican Colón','哥斯达黎加科朗'),
('CUP','Cuban Peso','古巴比索'),
('CVE','Cape Verdean Escudo','佛得角埃斯库多'),
('CZK','Czech Koruna','捷克克朗'),
('DJF','Djiboutian Franc','吉布提法郎'),
('DKK','Danish Krone','丹麦克朗'),
('DOP','Dominican Peso','多米尼加比索'),
('DZD','Algerian Dinar','阿尔及利亚第纳尔'),
('EGP','Egyptian Pound','埃及镑'),
('ERN','Eritrean Nakfa','厄立特里亚纳克法'),
('ETB','Ethiopian Birr','埃塞俄比亚比尔'),
('EUR','Euro','欧元'),
('FJD','Fijian Dollar','斐济元'),
('FKP','Falkland Islands Pound','福克兰群岛镑'),
('GBP','British Pound','英镑'),
('GEL','Georgian Lari','格鲁吉亚拉里'),
('GHS','Ghanaian Cedi','加纳塞地'),
('GIP','Gibraltar Pound','直布罗陀镑'),
('GMD','Gambian Dalasi','冈比亚达拉西'),
('GNF','Guinean Franc','几内亚法郎'),
('GTQ','Guatemalan Quetzal','危地马拉格查尔'),
('GYD','Guyanaese Dollar','圭亚那元'),
('HKD','Hong Kong Dollar','港元'),
('HNL','Honduran Lempira','洪都拉斯伦皮拉'),
('HTG','Haitian Gourde','海地古德'),
('HUF','Hungarian Forint','匈牙利福林'),
('IDR','Indonesian Rupiah','印度尼西亚卢比'),
('ILS','Israeli New Shekel','以色列新谢克尔'),
('INR','Indian Rupee','印度卢比'),
('IQD','Iraqi Dinar','伊拉克第纳尔'),
('IRR','Iranian Rial','伊朗里亚尔'),
('ISK','Icelandic Króna','冰岛克朗'),
('JMD','Jamaican Dollar','牙买加元'),
('JOD','Jordanian Dinar','约旦第纳尔'),
('JPY','Japanese Yen','日元'),
('KES','Kenyan Shilling','肯尼亚先令'),
('KGS','Kyrgyz Som','吉尔吉斯斯坦索姆'),
('KHR','Cambodian Riel','柬埔寨瑞尔'),
('KMF','Comorian Franc','科摩罗法郎'),
('KPW','North Korean Won','朝鲜元'),
('KRW','South Korean Won','韩元'),
('KWD','Kuwaiti Dinar','科威特第纳尔'),
('KYD','Cayman Islands Dollar','开曼元'),
('KZT','Kazakhstani Tenge','哈萨克斯坦坚戈'),
('LAK','Laotian Kip','老挝基普'),
('LBP','Lebanese Pound','黎巴嫩镑'),
('LKR','Sri Lankan Rupee','斯里兰卡卢比'),
('LRD','Liberian Dollar','利比里亚元'),
('LSL','Lesotho Loti','莱索托洛蒂'),
('LYD','Libyan Dinar','利比亚第纳尔'),
('MAD','Moroccan Dirham','摩洛哥迪拉姆'),
('MDL','Moldovan Leu','摩尔多瓦列伊'),
('MGA','Malagasy Ariary','马达加斯加阿里亚里'),
('MKD','Macedonian Denar','马其顿第纳尔'),
('MMK','Myanmar Kyat','缅甸元'),
('MNT','Mongolian Tugrik','蒙古图格里克'),
('MOP','Macanese Pataca','澳门币'),
('MUR','Mauritian Rupee','毛里求斯卢比'),
('MVR','Maldivian Rufiyaa','马尔代夫卢菲亚'),
('MWK','Malawian Kwacha','马拉维克瓦查'),
('MXN','Mexican Peso','墨西哥比索'),
('MYR','Malaysian Ringgit','马来西亚林吉特'),
('MZN','Mozambican Metical','莫桑比克美提卡'),
('NAD','Namibian Dollar','纳米比亚元'),
('NGN','Nigerian Naira','尼日利亚奈拉'),
('NIO','Nicaraguan Córdoba','尼加拉瓜科多巴'),
('NOK','Norwegian Krone','挪威克朗'),
('NPR','Nepalese Rupee','尼泊尔卢比'),
('NZD','New Zealand Dollar','新西兰元'),
('OMR','Omani Rial','阿曼里亚尔'),
('PAB','Panamanian Balboa','巴拿马巴波亚'),
('PEN','Peruvian Sol','秘鲁索尔'),
('PGK','Papua New Guinean Kina','巴布亚新几内亚基那'),
('PHP','Philippine Peso','菲律宾比索'),
('PKR','Pakistani Rupee','巴基斯坦卢比'),
('PLN','Polish Zloty','波兰兹罗提'),
('PYG','Paraguayan Guarani','巴拉圭瓜拉尼'),
('QAR','Qatari Riyal','卡塔尔里亚尔'),
('RON','Romanian Leu','罗马尼亚列伊'),
('RSD','Serbian Dinar','塞尔维亚第纳尔'),
('RUB','Russian Ruble','俄罗斯卢布'),
('RWF','Rwandan Franc','卢旺达法郎'),
('SAR','Saudi Riyal','沙特里亚尔'),
('SBD','Solomon Islands Dollar','所罗门群岛元'),
('SCR','Seychellois Rupee','塞舌尔卢比'),
('SDG','Sudanese Pound','苏丹镑'),
('SEK','Swedish Krona','瑞典克朗'),
('SGD','Singapore Dollar','新加坡元'),
('SHP','St. Helena Pound','圣赫勒拿群岛磅'),
('SOS','Somali Shilling','索马里先令'),
('SRD','Surinamese Dollar','苏里南元'),
('SSP','South Sudanese Pound','南苏丹镑'),
('STN','São Tomé & Príncipe Dobra','圣多美和普林西比多布拉'),
('SYP','Syrian Pound','叙利亚镑'),
('SZL','Swazi Lilangeni','斯威士兰里兰吉尼'),
('THB','Thai Baht','泰铢'),
('TJS','Tajikistani Somoni','塔吉克斯坦索莫尼'),
('TMT','Turkmenistani Manat','土库曼斯坦马纳特'),
('TND','Tunisian Dinar','突尼斯第纳尔'),
('TOP','Tongan Paʻanga','汤加潘加'),
('TRY','Turkish Lira','土耳其里拉'),
('TTD','Trinidad & Tobago Dollar','特立尼达和多巴哥元'),
('TWD','New Taiwan Dollar','新台币'),
('TZS','Tanzanian Shilling','坦桑尼亚先令'),
('UAH','Ukrainian Hryvnia','乌克兰格里夫纳'),
('UGX','Ugandan Shilling','乌干达先令'),
('USD','US Dollar','美元'),
('UYU','Uruguayan Peso','乌拉圭比索'),
('UZS','Uzbekistani Som','乌兹别克斯坦苏姆'),
('VND','Vietnamese Dong','越南盾'),
('VUV','Vanuatu Vatu','瓦努阿图瓦图'),
('WST','Samoan Tala','萨摩亚塔拉'),
('XAF','Central African CFA Franc','中非法郎'),
('XCD','East Caribbean Dollar','东加勒比元'),
('XOF','West African CFA Franc','西非法郎'),
('XPF','CFP Franc','太平洋法郎'),
('YER','Yemeni Rial','也门里亚尔'),
('ZAR','South African Rand','南非兰特'),
('ZMW','Zambian Kwacha','赞比亚克瓦查')
) AS labels(code, name_en, name_zh) WHERE labels.code = c.code;
-- Any later currency falls back to its stable code when rolling back this version.
UPDATE currencies SET name_en = code, name_zh = code WHERE name_en IS NULL;
ALTER TABLE currencies ALTER COLUMN name_en SET NOT NULL, ALTER COLUMN name_zh SET NOT NULL;
