// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FieldErrorLocation.
const (
	Body  FieldErrorLocation = "body"
	Path  FieldErrorLocation = "path"
	Query FieldErrorLocation = "query"
)

// Valid indicates whether the value is a known member of the FieldErrorLocation enum.
func (e FieldErrorLocation) Valid() bool {
	switch e {
	case Body:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PreferencesTheme.
const (
	Dark   PreferencesTheme = "dark"
	Light  PreferencesTheme = "light"
	System PreferencesTheme = "system"
)

// Valid indicates whether the value is a known member of the PreferencesTheme enum.
func (e PreferencesTheme) Valid() bool {
	switch e {
	case Dark:
		return true
	case Light:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessDatabase.
const (
	ReadinessDatabaseConnected ReadinessDatabase = "connected"
	ReadinessDatabaseDisabled  ReadinessDatabase = "disabled"
)

// Valid indicates whether the value is a known member of the ReadinessDatabase enum.
func (e ReadinessDatabase) Valid() bool {
	switch e {
	case ReadinessDatabaseConnected:
		return true
	case ReadinessDatabaseDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	ReadinessStatusOk ReadinessStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case ReadinessStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for StatusInputStatus.
const (
	StatusInputStatusActive   StatusInputStatus = "active"
	StatusInputStatusDisabled StatusInputStatus = "disabled"
)

// Valid indicates whether the value is a known member of the StatusInputStatus enum.
func (e StatusInputStatus) Valid() bool {
	switch e {
	case StatusInputStatusActive:
		return true
	case StatusInputStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for TenantRole.
const (
	Owner TenantRole = "owner"
)

// Valid indicates whether the value is a known member of the TenantRole enum.
func (e TenantRole) Valid() bool {
	switch e {
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UserContextInstanceRole.
const (
	UserContextInstanceRoleAdmin UserContextInstanceRole = "admin"
	UserContextInstanceRoleUser  UserContextInstanceRole = "user"
)

// Valid indicates whether the value is a known member of the UserContextInstanceRole enum.
func (e UserContextInstanceRole) Valid() bool {
	switch e {
	case UserContextInstanceRoleAdmin:
		return true
	case UserContextInstanceRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for APIVersion.
const (
	APIVersionN20260914 APIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the APIVersion enum.
func (e APIVersion) Valid() bool {
	switch e {
	case APIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for GetInstanceParamsXLedgerAPIVersion.
const (
	GetInstanceParamsXLedgerAPIVersionN20260914 GetInstanceParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the GetInstanceParamsXLedgerAPIVersion enum.
func (e GetInstanceParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case GetInstanceParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsXLedgerAPIVersion.
const (
	ListUsersParamsXLedgerAPIVersionN20260914 ListUsersParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the ListUsersParamsXLedgerAPIVersion enum.
func (e ListUsersParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case ListUsersParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for SetUserStatusParamsXLedgerAPIVersion.
const (
	SetUserStatusParamsXLedgerAPIVersionN20260914 SetUserStatusParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the SetUserStatusParamsXLedgerAPIVersion enum.
func (e SetUserStatusParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case SetUserStatusParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for ListBooksParamsXLedgerAPIVersion.
const (
	ListBooksParamsXLedgerAPIVersionN20260914 ListBooksParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the ListBooksParamsXLedgerAPIVersion enum.
func (e ListBooksParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case ListBooksParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for GetBookParamsXLedgerAPIVersion.
const (
	GetBookParamsXLedgerAPIVersionN20260914 GetBookParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the GetBookParamsXLedgerAPIVersion enum.
func (e GetBookParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case GetBookParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapParamsXLedgerAPIVersion.
const (
	BootstrapParamsXLedgerAPIVersionN20260914 BootstrapParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the BootstrapParamsXLedgerAPIVersion enum.
func (e BootstrapParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case BootstrapParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for GetMeParamsXLedgerAPIVersion.
const (
	GetMeParamsXLedgerAPIVersionN20260914 GetMeParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the GetMeParamsXLedgerAPIVersion enum.
func (e GetMeParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case GetMeParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePreferencesParamsXLedgerAPIVersion.
const (
	UpdatePreferencesParamsXLedgerAPIVersionN20260914 UpdatePreferencesParamsXLedgerAPIVersion = "2026-09-14"
)

// Valid indicates whether the value is a known member of the UpdatePreferencesParamsXLedgerAPIVersion enum.
func (e UpdatePreferencesParamsXLedgerAPIVersion) Valid() bool {
	switch e {
	case UpdatePreferencesParamsXLedgerAPIVersionN20260914:
		return true
	default:
		return false
	}
}

// Book defines model for Book.
type Book struct {
	BaseCurrency string             `json:"base_currency"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	TenantId     openapi_types.UUID `json:"tenant_id"`
}

// BookList defines model for BookList.
type BookList struct {
	Books []Book `json:"books"`
}

// BootstrapInput All three values are required only for a new identity. Existing identities may send an empty body or any supported initialization fields; stored settings are never overwritten. This database-dependent rule is enforced by the service.
type BootstrapInput struct {
	// BaseCurrency Required on first initialization: uppercase ISO 4217 code.
	BaseCurrency *string `json:"base_currency,omitempty"`

	// Locale Required on first initialization: BCP 47 language tag.
	Locale *string `json:"locale,omitempty"`

	// Timezone Required on first initialization: IANA timezone, excluding Local.
	Timezone *string `json:"timezone,omitempty"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Location FieldErrorLocation `json:"location"`
	Name     string             `json:"name"`
	Reason   string             `json:"reason"`
}

// FieldErrorLocation defines model for FieldError.Location.
type FieldErrorLocation string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Instance defines model for Instance.
type Instance struct {
	AdminUserId   openapi_types.UUID `json:"admin_user_id"`
	InitializedAt time.Time          `json:"initialized_at"`
}

// Preferences defines model for Preferences.
type Preferences struct {
	Locale   string           `json:"locale"`
	Theme    PreferencesTheme `json:"theme"`
	Timezone string           `json:"timezone"`
}

// PreferencesTheme defines model for Preferences.Theme.
type PreferencesTheme string

// PreferencesPatch At least one non-null field is required; validation is performed by the service.
type PreferencesPatch struct {
	// Locale BCP 47 locale. Null is ignored.
	Locale *string `json:"locale,omitempty"`

	// Theme system, light or dark. Null is ignored.
	Theme *string `json:"theme,omitempty"`

	// Timezone IANA timezone, excluding Local. Null is ignored.
	Timezone *string `json:"timezone,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail               string                 `json:"detail"`
	Errors               *[]FieldError          `json:"errors,omitempty"`
	Instance             string                 `json:"instance"`
	Status               int                    `json:"status"`
	SupportedVersions    *[]openapi_types.Date  `json:"supported_versions,omitempty"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Database ReadinessDatabase `json:"database"`
	Status   ReadinessStatus   `json:"status"`
}

// ReadinessDatabase defines model for Readiness.Database.
type ReadinessDatabase string

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// StatusInput defines model for StatusInput.
type StatusInput struct {
	// Reason Nonblank reason, maximum 1000 UTF-8 bytes.
	Reason string            `json:"reason"`
	Status StatusInputStatus `json:"status"`
}

// StatusInputStatus defines model for StatusInput.Status.
type StatusInputStatus string

// Tenant defines model for Tenant.
type Tenant struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Role TenantRole         `json:"role"`
}

// TenantRole defines model for Tenant.Role.
type TenantRole string

// User defines model for User.
type User struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Status      UserStatus         `json:"status"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// UserContext defines model for UserContext.
type UserContext struct {
	DefaultBook  Book                    `json:"default_book"`
	InstanceRole UserContextInstanceRole `json:"instance_role"`
	Preferences  Preferences             `json:"preferences"`
	Tenant       Tenant                  `json:"tenant"`
	User         User                    `json:"user"`
}

// UserContextInstanceRole defines model for UserContext.InstanceRole.
type UserContextInstanceRole string

// UserPage defines model for UserPage.
type UserPage struct {
	NextCursor *openapi_types.UUID `json:"next_cursor"`
	Users      []User              `json:"users"`
}

// APIVersion defines model for APIVersion.
type APIVersion string

// Error400 defines model for Error400.
type Error400 = Problem

// Error401 defines model for Error401.
type Error401 = Problem

// Error403 defines model for Error403.
type Error403 = Problem

// Error404 defines model for Error404.
type Error404 = Problem

// Error405 defines model for Error405.
type Error405 = Problem

// Error409 defines model for Error409.
type Error409 = Problem

// Error500 defines model for Error500.
type Error500 = Problem

// Error503 defines model for Error503.
type Error503 = Problem

// GetInstanceParams defines parameters for GetInstance.
type GetInstanceParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion GetInstanceParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// GetInstanceParamsXLedgerAPIVersion defines parameters for GetInstance.
type GetInstanceParamsXLedgerAPIVersion string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// After Exclusive UUID cursor.
	After *openapi_types.UUID `form:"after,omitempty" json:"after,omitempty"`
	Limit *int32              `form:"limit,omitempty" json:"limit,omitempty"`

	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion ListUsersParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// ListUsersParamsXLedgerAPIVersion defines parameters for ListUsers.
type ListUsersParamsXLedgerAPIVersion string

// SetUserStatusParams defines parameters for SetUserStatus.
type SetUserStatusParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion SetUserStatusParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// SetUserStatusParamsXLedgerAPIVersion defines parameters for SetUserStatus.
type SetUserStatusParamsXLedgerAPIVersion string

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion ListBooksParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// ListBooksParamsXLedgerAPIVersion defines parameters for ListBooks.
type ListBooksParamsXLedgerAPIVersion string

// GetBookParams defines parameters for GetBook.
type GetBookParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion GetBookParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// GetBookParamsXLedgerAPIVersion defines parameters for GetBook.
type GetBookParamsXLedgerAPIVersion string

// BootstrapParams defines parameters for Bootstrap.
type BootstrapParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion BootstrapParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// BootstrapParamsXLedgerAPIVersion defines parameters for Bootstrap.
type BootstrapParamsXLedgerAPIVersion string

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion GetMeParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// GetMeParamsXLedgerAPIVersion defines parameters for GetMe.
type GetMeParamsXLedgerAPIVersion string

// UpdatePreferencesParams defines parameters for UpdatePreferences.
type UpdatePreferencesParams struct {
	// XLedgerAPIVersion Exact contract date. Missing, malformed and retired dates are rejected before authentication.
	XLedgerAPIVersion UpdatePreferencesParamsXLedgerAPIVersion `json:"X-Ledger-API-Version"`
}

// UpdatePreferencesParamsXLedgerAPIVersion defines parameters for UpdatePreferences.
type UpdatePreferencesParamsXLedgerAPIVersion string

// SetUserStatusJSONRequestBody defines body for SetUserStatus for application/json ContentType.
type SetUserStatusJSONRequestBody = StatusInput

// BootstrapJSONRequestBody defines body for Bootstrap for application/json ContentType.
type BootstrapJSONRequestBody = BootstrapInput

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody = PreferencesPatch

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["supported_versions"]; found {
		err = json.Unmarshal(raw, &a.SupportedVersions)
		if err != nil {
			return fmt.Errorf("error reading 'supported_versions': %w", err)
		}
		delete(object, "supported_versions")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	if a.Errors != nil {
		object["errors"], err = json.Marshal(a.Errors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errors': %w", err)
		}
	}

	object["instance"], err = json.Marshal(a.Instance)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'instance': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	if a.SupportedVersions != nil {
		object["supported_versions"], err = json.Marshal(a.SupportedVersions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'supported_versions': %w", err)
		}
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetInstance Instance administrator and initialization time
	// (GET /api/v1/admin/instance)
	GetInstance(c *gin.Context, params GetInstanceParams)
	// ListUsers List internal users
	// (GET /api/v1/admin/users)
	ListUsers(c *gin.Context, params ListUsersParams)
	// SetUserStatus Suspend or restore a normal user
	// (PATCH /api/v1/admin/users/{user_id}/status)
	SetUserStatus(c *gin.Context, userId openapi_types.UUID, params SetUserStatusParams)
	// ListBooks List personal books
	// (GET /api/v1/books)
	ListBooks(c *gin.Context, params ListBooksParams)
	// GetBook Get a personal book
	// (GET /api/v1/books/{book_id})
	GetBook(c *gin.Context, bookId openapi_types.UUID, params GetBookParams)
	// Bootstrap Initialize personal space
	// (POST /api/v1/bootstrap)
	Bootstrap(c *gin.Context, params BootstrapParams)
	// GetMe Current user and personal space
	// (GET /api/v1/me)
	GetMe(c *gin.Context, params GetMeParams)
	// UpdatePreferences Update display preferences
	// (PATCH /api/v1/me/preferences)
	UpdatePreferences(c *gin.Context, params UpdatePreferencesParams)
	// GetHealth Process health
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// GetReadiness Database readiness
	// (GET /readyz)
	GetReadiness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInstanceParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion GetInstanceParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInstance(c, params)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", c.Request.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter after: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion ListUsersParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c, params)
}

// SetUserStatus operation middleware
func (siw *ServerInterfaceWrapper) SetUserStatus(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SetUserStatusParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion SetUserStatusParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetUserStatus(c, userId, params)
}

// ListBooks operation middleware
func (siw *ServerInterfaceWrapper) ListBooks(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBooksParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion ListBooksParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBooks(c, params)
}

// GetBook operation middleware
func (siw *ServerInterfaceWrapper) GetBook(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "book_id" -------------
	var bookId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "book_id", c.Param("book_id"), &bookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter book_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBookParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion GetBookParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBook(c, bookId, params)
}

// Bootstrap operation middleware
func (siw *ServerInterfaceWrapper) Bootstrap(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BootstrapParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion BootstrapParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Bootstrap(c, params)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMeParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion GetMeParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c, params)
}

// UpdatePreferences operation middleware
func (siw *ServerInterfaceWrapper) UpdatePreferences(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdatePreferencesParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Ledger-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Ledger-API-Version")]; found {
		var XLedgerAPIVersion UpdatePreferencesParamsXLedgerAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Ledger-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Ledger-API-Version", valueList[0], &XLedgerAPIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Ledger-API-Version: %w", err), http.StatusBadRequest)
			return
		}

		params.XLedgerAPIVersion = XLedgerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Ledger-API-Version is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePreferences(c, params)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/admin/instance", wrapper.GetInstance)
	router.GET(options.BaseURL+"/api/v1/admin/users", wrapper.ListUsers)
	router.PATCH(options.BaseURL+"/api/v1/admin/users/:user_id/status", wrapper.SetUserStatus)
	router.GET(options.BaseURL+"/api/v1/books", wrapper.ListBooks)
	router.GET(options.BaseURL+"/api/v1/books/:book_id", wrapper.GetBook)
	router.POST(options.BaseURL+"/api/v1/bootstrap", wrapper.Bootstrap)
	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetMe)
	router.PATCH(options.BaseURL+"/api/v1/me/preferences", wrapper.UpdatePreferences)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
}
