// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounting.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountingAccount = `-- name: AccountingAccount :one
SELECT id, tenant_id, book_id, name, role, kind, currency, category_id, system_code, archived, revision FROM accounts WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type AccountingAccountParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingAccount(ctx context.Context, arg AccountingAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, accountingAccount, arg.TenantID, arg.BookID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.Name,
		&i.Role,
		&i.Kind,
		&i.Currency,
		&i.CategoryID,
		&i.SystemCode,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const accountingAccounts = `-- name: AccountingAccounts :many
SELECT a.id, a.tenant_id, a.book_id, a.name, a.role, a.kind, a.currency, a.category_id, a.system_code, a.archived, a.revision,COALESCE((SELECT sum(p.amount) FROM postings p WHERE p.tenant_id=a.tenant_id AND p.book_id=a.book_id AND p.account_id=a.id),0)::text AS balance
FROM accounts a WHERE a.tenant_id=$1 AND a.book_id=$2 AND a.role='asset' ORDER BY a.archived,a.name,a.id
`

type AccountingAccountsParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
}

type AccountingAccountsRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	BookID     pgtype.UUID
	Name       string
	Role       string
	Kind       string
	Currency   string
	CategoryID pgtype.UUID
	SystemCode pgtype.Text
	Archived   bool
	Revision   int32
	Balance    string
}

func (q *Queries) AccountingAccounts(ctx context.Context, arg AccountingAccountsParams) ([]AccountingAccountsRow, error) {
	rows, err := q.db.Query(ctx, accountingAccounts, arg.TenantID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingAccountsRow{}
	for rows.Next() {
		var i AccountingAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BookID,
			&i.Name,
			&i.Role,
			&i.Kind,
			&i.Currency,
			&i.CategoryID,
			&i.SystemCode,
			&i.Archived,
			&i.Revision,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingAudit = `-- name: AccountingAudit :exec
INSERT INTO accounting_audit(id,tenant_id,book_id,actor_id,action,resource_id,before_data,after_data)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type AccountingAuditParams struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	BookID     pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	ResourceID pgtype.UUID
	BeforeData []byte
	AfterData  []byte
}

func (q *Queries) AccountingAudit(ctx context.Context, arg AccountingAuditParams) error {
	_, err := q.db.Exec(ctx, accountingAudit,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.ActorID,
		arg.Action,
		arg.ResourceID,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const accountingCategories = `-- name: AccountingCategories :many
SELECT id, tenant_id, book_id, parent_id, kind, name, name_zh, system_code, archived, revision FROM categories WHERE tenant_id=$1 AND book_id=$2 ORDER BY archived,name,id
`

type AccountingCategoriesParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
}

func (q *Queries) AccountingCategories(ctx context.Context, arg AccountingCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, accountingCategories, arg.TenantID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BookID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.NameZh,
			&i.SystemCode,
			&i.Archived,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingCategory = `-- name: AccountingCategory :one
SELECT id, tenant_id, book_id, parent_id, kind, name, name_zh, system_code, archived, revision FROM categories WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type AccountingCategoryParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingCategory(ctx context.Context, arg AccountingCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, accountingCategory, arg.TenantID, arg.BookID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.NameZh,
		&i.SystemCode,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const accountingCounterparties = `-- name: AccountingCounterparties :many
SELECT id, tenant_id, name, archived, revision FROM counterparties WHERE tenant_id=$1 ORDER BY archived,name,id
`

func (q *Queries) AccountingCounterparties(ctx context.Context, tenantID pgtype.UUID) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, accountingCounterparties, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Counterparty{}
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Archived,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingCounterparty = `-- name: AccountingCounterparty :one
SELECT id, tenant_id, name, archived, revision FROM counterparties WHERE tenant_id=$1 AND id=$2
`

type AccountingCounterpartyParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingCounterparty(ctx context.Context, arg AccountingCounterpartyParams) (Counterparty, error) {
	row := q.db.QueryRow(ctx, accountingCounterparty, arg.TenantID, arg.ID)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const accountingHistory = `-- name: AccountingHistory :many
SELECT revision,voided,data,actor_id,created_at FROM transaction_revisions
WHERE tenant_id=$1 AND book_id=$2 AND transaction_id=$3 ORDER BY revision DESC
`

type AccountingHistoryParams struct {
	TenantID      pgtype.UUID
	BookID        pgtype.UUID
	TransactionID pgtype.UUID
}

type AccountingHistoryRow struct {
	Revision  int32
	Voided    bool
	Data      []byte
	ActorID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AccountingHistory(ctx context.Context, arg AccountingHistoryParams) ([]AccountingHistoryRow, error) {
	rows, err := q.db.Query(ctx, accountingHistory, arg.TenantID, arg.BookID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingHistoryRow{}
	for rows.Next() {
		var i AccountingHistoryRow
		if err := rows.Scan(
			&i.Revision,
			&i.Voided,
			&i.Data,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingJournals = `-- name: AccountingJournals :many
SELECT jsonb_build_object('id',j.id,'revision',j.revision,'occurred_on',j.occurred_on,
'valuation_currency',j.valuation_currency,'reversal_of',j.reversal_of,
'postings',COALESCE((SELECT jsonb_agg(jsonb_build_object('account_id',p.account_id,'currency',a.currency,
'amount',p.amount::text,'valuation_amount',p.valuation_amount::text,'rate_numerator',p.rate_numerator::text,
'rate_denominator',p.rate_denominator::text,'rate_source',p.rate_source,'rate_date',p.rate_date) ORDER BY p.id)
FROM postings p JOIN accounts a ON a.id=p.account_id WHERE p.journal_id=j.id),'[]'::jsonb))::jsonb AS document
FROM journal_entries j WHERE j.tenant_id=$1 AND j.book_id=$2 AND j.transaction_id=$3 ORDER BY j.revision DESC,j.reversal_of NULLS LAST,j.id
`

type AccountingJournalsParams struct {
	TenantID      pgtype.UUID
	BookID        pgtype.UUID
	TransactionID pgtype.UUID
}

func (q *Queries) AccountingJournals(ctx context.Context, arg AccountingJournalsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, accountingJournals, arg.TenantID, arg.BookID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingLink = `-- name: AccountingLink :one
SELECT id, tenant_id, book_id, source_id, target_id, kind, created_by, created_at FROM transaction_links WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type AccountingLinkParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingLink(ctx context.Context, arg AccountingLinkParams) (TransactionLink, error) {
	row := q.db.QueryRow(ctx, accountingLink, arg.TenantID, arg.BookID, arg.ID)
	var i TransactionLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.SourceID,
		&i.TargetID,
		&i.Kind,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const accountingLinks = `-- name: AccountingLinks :many
SELECT id, tenant_id, book_id, source_id, target_id, kind, created_by, created_at FROM transaction_links WHERE tenant_id=$1 AND book_id=$2 AND ($3::uuid IS NULL OR source_id=$3 OR target_id=$3) ORDER BY created_at,id
`

type AccountingLinksParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	Column3  pgtype.UUID
}

func (q *Queries) AccountingLinks(ctx context.Context, arg AccountingLinksParams) ([]TransactionLink, error) {
	rows, err := q.db.Query(ctx, accountingLinks, arg.TenantID, arg.BookID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionLink{}
	for rows.Next() {
		var i TransactionLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BookID,
			&i.SourceID,
			&i.TargetID,
			&i.Kind,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingOpeningExists = `-- name: AccountingOpeningExists :one
SELECT EXISTS(SELECT 1 FROM transactions t JOIN transaction_revisions r ON r.transaction_id=t.id AND r.revision=t.revision
WHERE r.account_id=$1 AND r.kind='opening' AND t.status='posted')
`

func (q *Queries) AccountingOpeningExists(ctx context.Context, accountID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, accountingOpeningExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountingPageLinks = `-- name: AccountingPageLinks :many
SELECT id, tenant_id, book_id, source_id, target_id, kind, created_by, created_at FROM transaction_links WHERE tenant_id=$1 AND book_id=$2 AND (source_id=ANY($3::uuid[]) OR target_id=ANY($3::uuid[])) ORDER BY created_at,id
`

type AccountingPageLinksParams struct {
	TenantID       pgtype.UUID
	BookID         pgtype.UUID
	TransactionIds []pgtype.UUID
}

func (q *Queries) AccountingPageLinks(ctx context.Context, arg AccountingPageLinksParams) ([]TransactionLink, error) {
	rows, err := q.db.Query(ctx, accountingPageLinks, arg.TenantID, arg.BookID, arg.TransactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionLink{}
	for rows.Next() {
		var i TransactionLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BookID,
			&i.SourceID,
			&i.TargetID,
			&i.Kind,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingPostings = `-- name: AccountingPostings :many
SELECT id, tenant_id, book_id, journal_id, account_id, amount, valuation_amount, rate_numerator, rate_denominator, rate_source, rate_date FROM postings WHERE journal_id=$1 ORDER BY id
`

func (q *Queries) AccountingPostings(ctx context.Context, journalID pgtype.UUID) ([]Posting, error) {
	rows, err := q.db.Query(ctx, accountingPostings, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posting{}
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BookID,
			&i.JournalID,
			&i.AccountID,
			&i.Amount,
			&i.ValuationAmount,
			&i.RateNumerator,
			&i.RateDenominator,
			&i.RateSource,
			&i.RateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingRefunded = `-- name: AccountingRefunded :one
SELECT COALESCE(sum(r.amount),0)::text AS amount FROM transaction_links l
JOIN transactions t ON t.id=l.target_id JOIN transaction_revisions r ON r.transaction_id=t.id AND r.revision=t.revision
WHERE l.source_id=$1 AND l.kind='refund' AND t.status='posted' AND t.id<>$2
`

type AccountingRefundedParams struct {
	SourceID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingRefunded(ctx context.Context, arg AccountingRefundedParams) (string, error) {
	row := q.db.QueryRow(ctx, accountingRefunded, arg.SourceID, arg.ID)
	var amount string
	err := row.Scan(&amount)
	return amount, err
}

const accountingSummary = `-- name: AccountingSummary :many
SELECT a.currency,a.role,COALESCE(a.category_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS category_id,
sum(CASE WHEN a.role='income' THEN -p.amount ELSE p.amount END)::text AS amount
FROM postings p JOIN journal_entries j ON j.id=p.journal_id JOIN accounts a ON a.id=p.account_id
WHERE p.tenant_id=$1 AND p.book_id=$2 AND a.role IN ('income','expense')
AND ($3::date IS NULL OR j.occurred_on>=$3::date)
AND ($4::date IS NULL OR j.occurred_on<=$4::date)
GROUP BY a.currency,a.role,a.category_id ORDER BY a.currency,a.role,a.category_id
`

type AccountingSummaryParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type AccountingSummaryRow struct {
	Currency   string
	Role       string
	CategoryID pgtype.UUID
	Amount     string
}

func (q *Queries) AccountingSummary(ctx context.Context, arg AccountingSummaryParams) ([]AccountingSummaryRow, error) {
	rows, err := q.db.Query(ctx, accountingSummary,
		arg.TenantID,
		arg.BookID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingSummaryRow{}
	for rows.Next() {
		var i AccountingSummaryRow
		if err := rows.Scan(
			&i.Currency,
			&i.Role,
			&i.CategoryID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountingTransaction = `-- name: AccountingTransaction :one
SELECT accounting_transaction_json(t)::jsonb AS document FROM transactions t WHERE t.tenant_id=$1 AND t.book_id=$2 AND t.id=$3
`

type AccountingTransactionParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AccountingTransaction(ctx context.Context, arg AccountingTransactionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, accountingTransaction, arg.TenantID, arg.BookID, arg.ID)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const accountingTransactions = `-- name: AccountingTransactions :many
SELECT accounting_transaction_json(t)::jsonb AS document FROM transactions t
JOIN transaction_revisions r ON r.transaction_id=t.id AND r.revision=t.revision
WHERE t.tenant_id=$1 AND t.book_id=$2
AND ($3::boolean OR t.status='posted')
AND ($4::date IS NULL OR r.occurred_on>=$4::date)
AND ($5::date IS NULL OR r.occurred_on<=$5::date)
AND ($6::text IS NULL OR r.kind=$6::text)
AND ($7::uuid IS NULL OR r.account_id=$7::uuid OR r.to_account_id=$7::uuid)
AND ($8::text IS NULL OR EXISTS (SELECT 1 FROM accounts a WHERE a.id IN (r.account_id,r.to_account_id) AND a.currency=$8::text))
AND ($9::uuid IS NULL OR r.category_id=$9::uuid OR EXISTS (SELECT 1 FROM categories c WHERE c.id=r.category_id AND c.parent_id=$9::uuid))
AND ($10::uuid IS NULL OR r.counterparty_id=$10::uuid)
AND ($11::date IS NULL OR (r.occurred_on,t.created_at,t.id)<($11::date,$12::timestamptz,$13::uuid))
ORDER BY r.occurred_on DESC,t.created_at DESC,t.id DESC LIMIT $14
`

type AccountingTransactionsParams struct {
	TenantID       pgtype.UUID
	BookID         pgtype.UUID
	IncludeVoided  bool
	FromDate       pgtype.Date
	ToDate         pgtype.Date
	Kind           pgtype.Text
	AccountID      pgtype.UUID
	Currency       pgtype.Text
	CategoryID     pgtype.UUID
	CounterpartyID pgtype.UUID
	CursorDate     pgtype.Date
	CursorTime     pgtype.Timestamptz
	CursorID       pgtype.UUID
	PageSize       int32
}

func (q *Queries) AccountingTransactions(ctx context.Context, arg AccountingTransactionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, accountingTransactions,
		arg.TenantID,
		arg.BookID,
		arg.IncludeVoided,
		arg.FromDate,
		arg.ToDate,
		arg.Kind,
		arg.AccountID,
		arg.Currency,
		arg.CategoryID,
		arg.CounterpartyID,
		arg.CursorDate,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const archiveAccountingChildren = `-- name: ArchiveAccountingChildren :exec
UPDATE categories SET archived=true,revision=revision+1 WHERE tenant_id=$1 AND book_id=$2 AND parent_id=$3 AND NOT archived
`

type ArchiveAccountingChildrenParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ParentID pgtype.UUID
}

func (q *Queries) ArchiveAccountingChildren(ctx context.Context, arg ArchiveAccountingChildrenParams) error {
	_, err := q.db.Exec(ctx, archiveAccountingChildren, arg.TenantID, arg.BookID, arg.ParentID)
	return err
}

const authorizeAccounting = `-- name: AuthorizeAccounting :one
SELECT u.id FROM users u JOIN tenant_members m ON m.user_id=u.id JOIN tenants t ON t.id=m.tenant_id
WHERE u.id=$1 AND m.tenant_id=$2 AND u.status='active' AND m.status='active' AND t.status='active'
FOR SHARE OF u,m,t
`

type AuthorizeAccountingParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) AuthorizeAccounting(ctx context.Context, arg AuthorizeAccountingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, authorizeAccounting, arg.ID, arg.TenantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const changeAccountingAccount = `-- name: ChangeAccountingAccount :exec
UPDATE accounts SET name=$4,archived=$5,revision=revision+1 WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type ChangeAccountingAccountParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
	Name     string
	Archived bool
}

func (q *Queries) ChangeAccountingAccount(ctx context.Context, arg ChangeAccountingAccountParams) error {
	_, err := q.db.Exec(ctx, changeAccountingAccount,
		arg.TenantID,
		arg.BookID,
		arg.ID,
		arg.Name,
		arg.Archived,
	)
	return err
}

const changeAccountingCategory = `-- name: ChangeAccountingCategory :exec
UPDATE categories SET name=$4,name_zh=CASE WHEN name=$4 THEN name_zh ELSE '' END,archived=$5,revision=revision+1 WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type ChangeAccountingCategoryParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
	Name     string
	Archived bool
}

func (q *Queries) ChangeAccountingCategory(ctx context.Context, arg ChangeAccountingCategoryParams) error {
	_, err := q.db.Exec(ctx, changeAccountingCategory,
		arg.TenantID,
		arg.BookID,
		arg.ID,
		arg.Name,
		arg.Archived,
	)
	return err
}

const changeAccountingCounterparty = `-- name: ChangeAccountingCounterparty :exec
UPDATE counterparties SET name=$3,archived=$4,revision=revision+1 WHERE tenant_id=$1 AND id=$2
`

type ChangeAccountingCounterpartyParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
	Name     string
	Archived bool
}

func (q *Queries) ChangeAccountingCounterparty(ctx context.Context, arg ChangeAccountingCounterpartyParams) error {
	_, err := q.db.Exec(ctx, changeAccountingCounterparty,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Archived,
	)
	return err
}

const changeAccountingTransaction = `-- name: ChangeAccountingTransaction :exec
UPDATE transactions SET revision=$4,status=$5 WHERE tenant_id=$1 AND book_id=$2 AND id=$3
`

type ChangeAccountingTransactionParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
	Revision int32
	Status   string
}

func (q *Queries) ChangeAccountingTransaction(ctx context.Context, arg ChangeAccountingTransactionParams) error {
	_, err := q.db.Exec(ctx, changeAccountingTransaction,
		arg.TenantID,
		arg.BookID,
		arg.ID,
		arg.Revision,
		arg.Status,
	)
	return err
}

const currentAccountingJournal = `-- name: CurrentAccountingJournal :one
SELECT j.id, j.tenant_id, j.book_id, j.transaction_id, j.revision, j.occurred_on, j.valuation_currency, j.reversal_of, j.sealed FROM journal_entries j WHERE j.transaction_id=$1 AND j.revision=$2 AND j.reversal_of IS NULL
`

type CurrentAccountingJournalParams struct {
	TransactionID pgtype.UUID
	Revision      int32
}

func (q *Queries) CurrentAccountingJournal(ctx context.Context, arg CurrentAccountingJournalParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, currentAccountingJournal, arg.TransactionID, arg.Revision)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.TransactionID,
		&i.Revision,
		&i.OccurredOn,
		&i.ValuationCurrency,
		&i.ReversalOf,
		&i.Sealed,
	)
	return i, err
}

const insertAccountingAccount = `-- name: InsertAccountingAccount :one
INSERT INTO accounts(id,tenant_id,book_id,name,role,kind,currency,category_id,system_code)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, tenant_id, book_id, name, role, kind, currency, category_id, system_code, archived, revision
`

type InsertAccountingAccountParams struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	BookID     pgtype.UUID
	Name       string
	Role       string
	Kind       string
	Currency   string
	CategoryID pgtype.UUID
	SystemCode pgtype.Text
}

func (q *Queries) InsertAccountingAccount(ctx context.Context, arg InsertAccountingAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccountingAccount,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.Name,
		arg.Role,
		arg.Kind,
		arg.Currency,
		arg.CategoryID,
		arg.SystemCode,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.Name,
		&i.Role,
		&i.Kind,
		&i.Currency,
		&i.CategoryID,
		&i.SystemCode,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const insertAccountingCategory = `-- name: InsertAccountingCategory :one
INSERT INTO categories(id,tenant_id,book_id,parent_id,kind,name,name_zh,system_code)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (tenant_id,book_id,system_code) DO UPDATE SET system_code=EXCLUDED.system_code RETURNING id, tenant_id, book_id, parent_id, kind, name, name_zh, system_code, archived, revision
`

type InsertAccountingCategoryParams struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	BookID     pgtype.UUID
	ParentID   pgtype.UUID
	Kind       string
	Name       string
	NameZh     string
	SystemCode pgtype.Text
}

func (q *Queries) InsertAccountingCategory(ctx context.Context, arg InsertAccountingCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertAccountingCategory,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.NameZh,
		arg.SystemCode,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.NameZh,
		&i.SystemCode,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const insertAccountingCounterparty = `-- name: InsertAccountingCounterparty :one
INSERT INTO counterparties(id,tenant_id,name) VALUES ($1,$2,$3) RETURNING id, tenant_id, name, archived, revision
`

type InsertAccountingCounterpartyParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Name     string
}

func (q *Queries) InsertAccountingCounterparty(ctx context.Context, arg InsertAccountingCounterpartyParams) (Counterparty, error) {
	row := q.db.QueryRow(ctx, insertAccountingCounterparty, arg.ID, arg.TenantID, arg.Name)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}

const insertAccountingJournal = `-- name: InsertAccountingJournal :exec
INSERT INTO journal_entries(id,tenant_id,book_id,transaction_id,revision,occurred_on,valuation_currency,reversal_of)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertAccountingJournalParams struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BookID            pgtype.UUID
	TransactionID     pgtype.UUID
	Revision          int32
	OccurredOn        pgtype.Date
	ValuationCurrency string
	ReversalOf        pgtype.UUID
}

func (q *Queries) InsertAccountingJournal(ctx context.Context, arg InsertAccountingJournalParams) error {
	_, err := q.db.Exec(ctx, insertAccountingJournal,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.TransactionID,
		arg.Revision,
		arg.OccurredOn,
		arg.ValuationCurrency,
		arg.ReversalOf,
	)
	return err
}

const insertAccountingLink = `-- name: InsertAccountingLink :one
INSERT INTO transaction_links(id,tenant_id,book_id,source_id,target_id,kind,created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, tenant_id, book_id, source_id, target_id, kind, created_by, created_at
`

type InsertAccountingLinkParams struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BookID    pgtype.UUID
	SourceID  pgtype.UUID
	TargetID  pgtype.UUID
	Kind      string
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertAccountingLink(ctx context.Context, arg InsertAccountingLinkParams) (TransactionLink, error) {
	row := q.db.QueryRow(ctx, insertAccountingLink,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.SourceID,
		arg.TargetID,
		arg.Kind,
		arg.CreatedBy,
	)
	var i TransactionLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.SourceID,
		&i.TargetID,
		&i.Kind,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAccountingPosting = `-- name: InsertAccountingPosting :exec
INSERT INTO postings(id,tenant_id,book_id,journal_id,account_id,amount,valuation_amount,rate_numerator,rate_denominator,rate_source,rate_date)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertAccountingPostingParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BookID          pgtype.UUID
	JournalID       pgtype.UUID
	AccountID       pgtype.UUID
	Amount          pgtype.Numeric
	ValuationAmount pgtype.Numeric
	RateNumerator   pgtype.Numeric
	RateDenominator pgtype.Numeric
	RateSource      string
	RateDate        pgtype.Date
}

func (q *Queries) InsertAccountingPosting(ctx context.Context, arg InsertAccountingPostingParams) error {
	_, err := q.db.Exec(ctx, insertAccountingPosting,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.JournalID,
		arg.AccountID,
		arg.Amount,
		arg.ValuationAmount,
		arg.RateNumerator,
		arg.RateDenominator,
		arg.RateSource,
		arg.RateDate,
	)
	return err
}

const insertAccountingRevision = `-- name: InsertAccountingRevision :exec
INSERT INTO transaction_revisions(tenant_id,book_id,transaction_id,revision,kind,occurred_on,account_id,to_account_id,category_id,counterparty_id,amount,to_amount,original_id,data,voided,actor_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type InsertAccountingRevisionParams struct {
	TenantID       pgtype.UUID
	BookID         pgtype.UUID
	TransactionID  pgtype.UUID
	Revision       int32
	Kind           string
	OccurredOn     pgtype.Date
	AccountID      pgtype.UUID
	ToAccountID    pgtype.UUID
	CategoryID     pgtype.UUID
	CounterpartyID pgtype.UUID
	Amount         pgtype.Numeric
	ToAmount       pgtype.Numeric
	OriginalID     pgtype.UUID
	Data           []byte
	Voided         bool
	ActorID        pgtype.UUID
}

func (q *Queries) InsertAccountingRevision(ctx context.Context, arg InsertAccountingRevisionParams) error {
	_, err := q.db.Exec(ctx, insertAccountingRevision,
		arg.TenantID,
		arg.BookID,
		arg.TransactionID,
		arg.Revision,
		arg.Kind,
		arg.OccurredOn,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.CounterpartyID,
		arg.Amount,
		arg.ToAmount,
		arg.OriginalID,
		arg.Data,
		arg.Voided,
		arg.ActorID,
	)
	return err
}

const insertAccountingTransaction = `-- name: InsertAccountingTransaction :exec
INSERT INTO transactions(id,tenant_id,book_id,revision,status,created_by) VALUES ($1,$2,$3,1,'posted',$4)
`

type InsertAccountingTransactionParams struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BookID    pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertAccountingTransaction(ctx context.Context, arg InsertAccountingTransactionParams) error {
	_, err := q.db.Exec(ctx, insertAccountingTransaction,
		arg.ID,
		arg.TenantID,
		arg.BookID,
		arg.CreatedBy,
	)
	return err
}

const lockAccountingBook = `-- name: LockAccountingBook :one
SELECT id FROM books WHERE tenant_id=$1 AND id=$2 FOR UPDATE
`

type LockAccountingBookParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) LockAccountingBook(ctx context.Context, arg LockAccountingBookParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAccountingBook, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockAccountingTenant = `-- name: LockAccountingTenant :one
SELECT id FROM tenants WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAccountingTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAccountingTenant, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const readAccountingOperation = `-- name: ReadAccountingOperation :one
SELECT request_hash,response FROM accounting_operations WHERE tenant_id=$1 AND key=$2
`

type ReadAccountingOperationParams struct {
	TenantID pgtype.UUID
	Key      pgtype.UUID
}

type ReadAccountingOperationRow struct {
	RequestHash string
	Response    []byte
}

func (q *Queries) ReadAccountingOperation(ctx context.Context, arg ReadAccountingOperationParams) (ReadAccountingOperationRow, error) {
	row := q.db.QueryRow(ctx, readAccountingOperation, arg.TenantID, arg.Key)
	var i ReadAccountingOperationRow
	err := row.Scan(&i.RequestHash, &i.Response)
	return i, err
}

const removeAccountingLink = `-- name: RemoveAccountingLink :exec
DELETE FROM transaction_links WHERE tenant_id=$1 AND book_id=$2 AND id=$3 AND kind='related'
`

type RemoveAccountingLinkParams struct {
	TenantID pgtype.UUID
	BookID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) RemoveAccountingLink(ctx context.Context, arg RemoveAccountingLinkParams) error {
	_, err := q.db.Exec(ctx, removeAccountingLink, arg.TenantID, arg.BookID, arg.ID)
	return err
}

const saveAccountingOperation = `-- name: SaveAccountingOperation :exec
INSERT INTO accounting_operations(tenant_id,key,request_hash,response) VALUES ($1,$2,$3,$4)
`

type SaveAccountingOperationParams struct {
	TenantID    pgtype.UUID
	Key         pgtype.UUID
	RequestHash string
	Response    []byte
}

func (q *Queries) SaveAccountingOperation(ctx context.Context, arg SaveAccountingOperationParams) error {
	_, err := q.db.Exec(ctx, saveAccountingOperation,
		arg.TenantID,
		arg.Key,
		arg.RequestHash,
		arg.Response,
	)
	return err
}

const sealAccountingJournal = `-- name: SealAccountingJournal :exec
UPDATE journal_entries SET sealed=true WHERE id=$1
`

func (q *Queries) SealAccountingJournal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sealAccountingJournal, id)
	return err
}

const systemAccountingAccount = `-- name: SystemAccountingAccount :one
SELECT id, tenant_id, book_id, name, role, kind, currency, category_id, system_code, archived, revision FROM accounts WHERE tenant_id=$1 AND book_id=$2 AND currency=$3
AND (($4::uuid IS NOT NULL AND category_id=$4::uuid)
OR ($5::text IS NOT NULL AND system_code=$5::text))
`

type SystemAccountingAccountParams struct {
	TenantID   pgtype.UUID
	BookID     pgtype.UUID
	Currency   string
	CategoryID pgtype.UUID
	SystemCode pgtype.Text
}

func (q *Queries) SystemAccountingAccount(ctx context.Context, arg SystemAccountingAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, systemAccountingAccount,
		arg.TenantID,
		arg.BookID,
		arg.Currency,
		arg.CategoryID,
		arg.SystemCode,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BookID,
		&i.Name,
		&i.Role,
		&i.Kind,
		&i.Currency,
		&i.CategoryID,
		&i.SystemCode,
		&i.Archived,
		&i.Revision,
	)
	return i, err
}
