// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlgen

import (
	"context"
)

// iteratorForInsertMarketRates implements pgx.CopyFromSource.
type iteratorForInsertMarketRates struct {
	rows                 []InsertMarketRatesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertMarketRates) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertMarketRates) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SnapshotID,
		r.rows[0].BaseCurrency,
		r.rows[0].QuoteCurrency,
		r.rows[0].Rate,
		r.rows[0].RateDate,
		r.rows[0].Providers,
	}, nil
}

func (r iteratorForInsertMarketRates) Err() error {
	return nil
}

func (q *Queries) InsertMarketRates(ctx context.Context, arg []InsertMarketRatesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"market_rates"}, []string{"id", "snapshot_id", "base_currency", "quote_currency", "rate", "rate_date", "providers"}, &iteratorForInsertMarketRates{rows: arg})
}
