// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindPersonalTenant = `-- name: BindPersonalTenant :exec
INSERT INTO personal_tenant_bindings (user_id, tenant_id, default_book_id) VALUES ($1, $2, $3)
`

type BindPersonalTenantParams struct {
	UserID        pgtype.UUID
	TenantID      pgtype.UUID
	DefaultBookID pgtype.UUID
}

func (q *Queries) BindPersonalTenant(ctx context.Context, arg BindPersonalTenantParams) error {
	_, err := q.db.Exec(ctx, bindPersonalTenant, arg.UserID, arg.TenantID, arg.DefaultBookID)
	return err
}

const claimInstance = `-- name: ClaimInstance :exec
UPDATE instance_state SET admin_user_id = $1, initialized_at = now() WHERE singleton = true AND admin_user_id IS NULL
`

func (q *Queries) ClaimInstance(ctx context.Context, adminUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, claimInstance, adminUserID)
	return err
}

const createAdminAudit = `-- name: CreateAdminAudit :exec
INSERT INTO admin_audit_events (id, actor_id, target_user_id, previous_status, new_status, reason)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAdminAuditParams struct {
	ID             pgtype.UUID
	ActorID        pgtype.UUID
	TargetUserID   pgtype.UUID
	PreviousStatus string
	NewStatus      string
	Reason         string
}

func (q *Queries) CreateAdminAudit(ctx context.Context, arg CreateAdminAuditParams) error {
	_, err := q.db.Exec(ctx, createAdminAudit,
		arg.ID,
		arg.ActorID,
		arg.TargetUserID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
	)
	return err
}

const createBook = `-- name: CreateBook :exec
INSERT INTO books (id, tenant_id, name, base_currency) VALUES ($1, $2, 'Main', $3)
`

type CreateBookParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	BaseCurrency string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) error {
	_, err := q.db.Exec(ctx, createBook, arg.ID, arg.TenantID, arg.BaseCurrency)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO user_identities (issuer, subject, user_id) VALUES ($1, $2, $3)
`

type CreateIdentityParams struct {
	Issuer  string
	Subject string
	UserID  pgtype.UUID
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity, arg.Issuer, arg.Subject, arg.UserID)
	return err
}

const createOwner = `-- name: CreateOwner :exec
INSERT INTO tenant_members (tenant_id, user_id) VALUES ($1, $2)
`

type CreateOwnerParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) error {
	_, err := q.db.Exec(ctx, createOwner, arg.TenantID, arg.UserID)
	return err
}

const createPreferences = `-- name: CreatePreferences :exec
INSERT INTO user_preferences (user_id, locale, timezone) VALUES ($1, $2, $3)
`

type CreatePreferencesParams struct {
	UserID   pgtype.UUID
	Locale   string
	Timezone string
}

func (q *Queries) CreatePreferences(ctx context.Context, arg CreatePreferencesParams) error {
	_, err := q.db.Exec(ctx, createPreferences, arg.UserID, arg.Locale, arg.Timezone)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name) VALUES ($1, 'Personal')
`

func (q *Queries) CreateTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createTenant, id)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const findIdentity = `-- name: FindIdentity :one
SELECT user_id FROM user_identities WHERE issuer = $1 AND subject = $2
`

type FindIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) FindIdentity(ctx context.Context, arg FindIdentityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findIdentity, arg.Issuer, arg.Subject)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getBook = `-- name: GetBook :one
SELECT id, tenant_id, name, base_currency, created_at FROM books WHERE tenant_id = $1 AND id = $2
`

type GetBookParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetBook(ctx context.Context, arg GetBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, arg.TenantID, arg.ID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const getInstance = `-- name: GetInstance :one
SELECT singleton, admin_user_id, initialized_at FROM instance_state WHERE singleton = true
`

func (q *Queries) GetInstance(ctx context.Context) (InstanceState, error) {
	row := q.db.QueryRow(ctx, getInstance)
	var i InstanceState
	err := row.Scan(&i.Singleton, &i.AdminUserID, &i.InitializedAt)
	return i, err
}

const getUserContext = `-- name: GetUserContext :one
SELECT u.id, u.display_name, u.status, p.tenant_id, t.name AS tenant_name, t.status AS tenant_status,
 m.status AS member_status, m.role, p.default_book_id, b.name AS book_name, b.base_currency,
 pref.locale, pref.timezone, pref.theme, (s.admin_user_id = u.id)::boolean AS is_admin
FROM users u
JOIN personal_tenant_bindings p ON p.user_id = u.id
JOIN tenants t ON t.id = p.tenant_id
JOIN tenant_members m ON m.tenant_id = t.id AND m.user_id = u.id
JOIN books b ON b.tenant_id = t.id AND b.id = p.default_book_id
JOIN user_preferences pref ON pref.user_id = u.id
CROSS JOIN instance_state s
WHERE u.id = $1
`

type GetUserContextRow struct {
	ID            pgtype.UUID
	DisplayName   string
	Status        string
	TenantID      pgtype.UUID
	TenantName    string
	TenantStatus  string
	MemberStatus  string
	Role          string
	DefaultBookID pgtype.UUID
	BookName      string
	BaseCurrency  string
	Locale        string
	Timezone      string
	Theme         string
	IsAdmin       bool
}

func (q *Queries) GetUserContext(ctx context.Context, id pgtype.UUID) (GetUserContextRow, error) {
	row := q.db.QueryRow(ctx, getUserContext, id)
	var i GetUserContextRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.TenantID,
		&i.TenantName,
		&i.TenantStatus,
		&i.MemberStatus,
		&i.Role,
		&i.DefaultBookID,
		&i.BookName,
		&i.BaseCurrency,
		&i.Locale,
		&i.Timezone,
		&i.Theme,
		&i.IsAdmin,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, tenant_id, name, base_currency, created_at FROM books WHERE tenant_id = $1 ORDER BY id
`

func (q *Queries) ListBooks(ctx context.Context, tenantID pgtype.UUID) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.BaseCurrency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, status, created_at FROM users
WHERE ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id LIMIT $1
`

type ListUsersParams struct {
	Limit   int32
	AfterID pgtype.UUID
}

type ListUsersRow struct {
	ID          pgtype.UUID
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstance = `-- name: LockInstance :one
SELECT singleton, admin_user_id, initialized_at FROM instance_state WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockInstance(ctx context.Context) (InstanceState, error) {
	row := q.db.QueryRow(ctx, lockInstance)
	var i InstanceState
	err := row.Scan(&i.Singleton, &i.AdminUserID, &i.InitializedAt)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id, display_name, status, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE user_preferences SET locale = COALESCE($2::text, locale),
 timezone = COALESCE($3::text, timezone), theme = COALESCE($4::text, theme)
WHERE user_id = $1 RETURNING user_id, locale, timezone, theme
`

type UpdatePreferencesParams struct {
	UserID   pgtype.UUID
	Locale   pgtype.Text
	Timezone pgtype.Text
	Theme    pgtype.Text
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.UserID,
		arg.Locale,
		arg.Timezone,
		arg.Theme,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Locale,
		&i.Timezone,
		&i.Theme,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
