// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditEvent struct {
	ID             pgtype.UUID
	ActorID        pgtype.UUID
	TargetUserID   pgtype.UUID
	PreviousStatus string
	NewStatus      string
	Reason         string
	CreatedAt      pgtype.Timestamptz
}

type Book struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Name         string
	BaseCurrency string
	CreatedAt    pgtype.Timestamptz
}

type InstanceState struct {
	Singleton     bool
	AdminUserID   pgtype.UUID
	InitializedAt pgtype.Timestamptz
}

type PersonalTenantBinding struct {
	UserID        pgtype.UUID
	TenantID      pgtype.UUID
	DefaultBookID pgtype.UUID
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Kind      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type TenantMember struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	Status   string
}

type User struct {
	ID          pgtype.UUID
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserIdentity struct {
	Issuer  string
	Subject string
	UserID  pgtype.UUID
}

type UserPreference struct {
	UserID   pgtype.UUID
	Locale   string
	Timezone string
	Theme    string
}
