// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentMarketRateSnapshot = `-- name: CurrentMarketRateSnapshot :one
SELECT s.id, s.snapshot_date, s.source, s.source_version, s.provider_filter, s.base_currency, s.status, s.fetched_at, s.published_at, s.created_at FROM market_rate_snapshots s
WHERE s.status='published' AND s.base_currency=$1
AND EXISTS (SELECT 1 FROM market_rates r WHERE r.snapshot_id=s.id AND r.quote_currency=$2)
AND ($3::text IS NULL OR EXISTS (SELECT 1 FROM market_rates r2 WHERE r2.snapshot_id=s.id AND r2.quote_currency=$3::text))
ORDER BY s.snapshot_date DESC,s.published_at DESC
LIMIT 1
`

type CurrentMarketRateSnapshotParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Leg2          pgtype.Text
}

// Newest published snapshot that carries every leg the requested pair needs, so
// a provider coverage change falls back to an older complete batch instead of
// serving a partial conversion.
func (q *Queries) CurrentMarketRateSnapshot(ctx context.Context, arg CurrentMarketRateSnapshotParams) (MarketRateSnapshot, error) {
	row := q.db.QueryRow(ctx, currentMarketRateSnapshot, arg.BaseCurrency, arg.QuoteCurrency, arg.Leg2)
	var i MarketRateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotDate,
		&i.Source,
		&i.SourceVersion,
		&i.ProviderFilter,
		&i.BaseCurrency,
		&i.Status,
		&i.FetchedAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMarketRates = `-- name: DeleteMarketRates :exec
DELETE FROM market_rates WHERE snapshot_id=$1
`

func (q *Queries) DeleteMarketRates(ctx context.Context, snapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarketRates, snapshotID)
	return err
}

const findMarketRateSnapshot = `-- name: FindMarketRateSnapshot :one
SELECT id, snapshot_date, source, source_version, provider_filter, base_currency, status, fetched_at, published_at, created_at FROM market_rate_snapshots
WHERE snapshot_date=$1 AND source=$2 AND source_version=$3 AND provider_filter=$4
FOR UPDATE
`

type FindMarketRateSnapshotParams struct {
	SnapshotDate   pgtype.Date
	Source         string
	SourceVersion  string
	ProviderFilter string
}

func (q *Queries) FindMarketRateSnapshot(ctx context.Context, arg FindMarketRateSnapshotParams) (MarketRateSnapshot, error) {
	row := q.db.QueryRow(ctx, findMarketRateSnapshot,
		arg.SnapshotDate,
		arg.Source,
		arg.SourceVersion,
		arg.ProviderFilter,
	)
	var i MarketRateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotDate,
		&i.Source,
		&i.SourceVersion,
		&i.ProviderFilter,
		&i.BaseCurrency,
		&i.Status,
		&i.FetchedAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasPublishedMarketRateSnapshot = `-- name: HasPublishedMarketRateSnapshot :one
SELECT id FROM market_rate_snapshots
WHERE snapshot_date=$1 AND source=$2 AND source_version=$3 AND provider_filter=$4 AND status='published'
`

type HasPublishedMarketRateSnapshotParams struct {
	SnapshotDate   pgtype.Date
	Source         string
	SourceVersion  string
	ProviderFilter string
}

func (q *Queries) HasPublishedMarketRateSnapshot(ctx context.Context, arg HasPublishedMarketRateSnapshotParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, hasPublishedMarketRateSnapshot,
		arg.SnapshotDate,
		arg.Source,
		arg.SourceVersion,
		arg.ProviderFilter,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMarketRateSnapshot = `-- name: InsertMarketRateSnapshot :exec
INSERT INTO market_rate_snapshots(id,snapshot_date,source,source_version,provider_filter,base_currency,status,fetched_at)
VALUES ($1,$2,$3,$4,$5,$6,'pending',$7)
ON CONFLICT (snapshot_date,source,source_version,provider_filter) DO NOTHING
`

type InsertMarketRateSnapshotParams struct {
	ID             pgtype.UUID
	SnapshotDate   pgtype.Date
	Source         string
	SourceVersion  string
	ProviderFilter string
	BaseCurrency   string
	FetchedAt      pgtype.Timestamptz
}

func (q *Queries) InsertMarketRateSnapshot(ctx context.Context, arg InsertMarketRateSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertMarketRateSnapshot,
		arg.ID,
		arg.SnapshotDate,
		arg.Source,
		arg.SourceVersion,
		arg.ProviderFilter,
		arg.BaseCurrency,
		arg.FetchedAt,
	)
	return err
}

type InsertMarketRatesParams struct {
	ID            pgtype.UUID
	SnapshotID    pgtype.UUID
	BaseCurrency  string
	QuoteCurrency string
	Rate          pgtype.Numeric
	RateDate      pgtype.Date
	Providers     []string
}

const latestPublishedMarketSnapshotDate = `-- name: LatestPublishedMarketSnapshotDate :one
SELECT max(snapshot_date)::date FROM market_rate_snapshots WHERE status='published'
`

func (q *Queries) LatestPublishedMarketSnapshotDate(ctx context.Context) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, latestPublishedMarketSnapshotDate)
	var column_1 pgtype.Date
	err := row.Scan(&column_1)
	return column_1, err
}

const marketSnapshotRates = `-- name: MarketSnapshotRates :many
SELECT id, snapshot_id, base_currency, quote_currency, rate, rate_date, providers FROM market_rates WHERE snapshot_id=$1 AND quote_currency=ANY($2::text[]) ORDER BY quote_currency
`

type MarketSnapshotRatesParams struct {
	SnapshotID pgtype.UUID
	Quotes     []string
}

func (q *Queries) MarketSnapshotRates(ctx context.Context, arg MarketSnapshotRatesParams) ([]MarketRate, error) {
	rows, err := q.db.Query(ctx, marketSnapshotRates, arg.SnapshotID, arg.Quotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketRate{}
	for rows.Next() {
		var i MarketRate
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.Rate,
			&i.RateDate,
			&i.Providers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneMarketRateSnapshots = `-- name: PruneMarketRateSnapshots :exec
DELETE FROM market_rate_snapshots WHERE snapshot_date < $1
`

func (q *Queries) PruneMarketRateSnapshots(ctx context.Context, snapshotDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, pruneMarketRateSnapshots, snapshotDate)
	return err
}

const publishMarketRateSnapshot = `-- name: PublishMarketRateSnapshot :exec
UPDATE market_rate_snapshots SET status='published',published_at=$2 WHERE id=$1
`

type PublishMarketRateSnapshotParams struct {
	ID          pgtype.UUID
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) PublishMarketRateSnapshot(ctx context.Context, arg PublishMarketRateSnapshotParams) error {
	_, err := q.db.Exec(ctx, publishMarketRateSnapshot, arg.ID, arg.PublishedAt)
	return err
}
